### PR TITLE
Modified stan code

### PR DESCRIPTION
**Pull request by otthii**
I tried to update "model/stan/model.stan" according to the latest "model.bug" and some of parts (especially categorizing fisheries and species group variables) were changed for optimization the MCMC sampling. 
The part of generating total population named "ntot" inside the model was removed from the code because such setting gives serious (and not necessary) uncertainty for estimated parameters on the MCMC algorithm. "model/prepare-model-data.r" was also update for the requirement making input data for Stan. 
At this point, MCMC sampling on Stan does not work well because of poor initial values. 
I feel this model needs further modifications for sampling optimization so I'll try to update that.

### CODE REVIEW

**Comment by edwardabraham** [comment]
Thanks very much  for this. Great to have your experience here. @yvanrichard  will review the model (hopefullly today) and may make some changes. We will also talk about the `n_tot` issue. The reason we have it in the model is so that the chains for the vulnerability and the population size are correctly correlated. We are then careful to track this through, using the same population size, when we calculate the PST (the population productivity part of the risk). One approach may be to prepare a model with and without uncertainty on the population, so that we can explore the effect that this has on the uncertainty in the estimated fatalities and risk.

**Comment by edwardabraham** [comment]
Hi @otthii ... we will work on integrating your Stan model in with the rest of the project today. This will involve changing  quite a few lines in your code. If you hold off making any more changes to your code, we will let you know when we are done. Thanks!

**Comment by otthii** [comment]
Hello @edwardabraham, 
it is absolutely no problem to change the code.
Thank you very much for your great work.

**Comment by yvanrichard** [comment]
Hi @otthii 
Thank you for your contribution. Have you identified what is causing the problem with initial values? The model runs fine in JAGS so I find it strange. Your parametrisation is a bit different but it makes sense as far as I can tell. I have been trying out several modifications but still cannot make it work.

**Pull request merged**
