### PR TITLE
Model framework has been totally changed.

### PR DESCRIPTION
**Pull request by otthii**
I've totally changed the model framework in `model/stan/model.stan` to estimate catchability, observable rate, mortality at catch and to predict APF.   
List of the changes are noted as belows;  
### Major changes
- Removing `fmax` functions from all Poisson sampling. This is completely not good to produce proper posteriors.
  - Instead of that, link functions are introduced into the model.
  - Those link functions can be transformed as log or logit so that we are now liberated from consraints of parameter ranges
  - It also enables to express relationships of parameters as a liner equation.
- Considering the chain of causality about occurrence of seabird bycatch, order of sampling equations have been changed.
  - Total (and true) number of caught birds (related to `q`) should be firstly solved and `p_obserbable` and `p_live_cap` are following.
  - `p_observable` and `p_live_cap` are now sampled from binomial distribution.
- `p_live_cap` is now estimated just based on observed captures (`DEAD_CAPTURES_O` and `LIVE_CAPTURES_O`)
- `p_observable` is now directly estimated inside the model with using raw data of Brothers et al. 2010.
  - While it gives a very weak effect on posterior when the result is applied only to prior, it is effective to estimate the parameter simultaneously inside the model.
- The part of `p_identified` is now commented out. 
  - Previous `p_identified` was incorrectly defined.
  - This value was calculated from ratio of unidentified birds toward the identified all bird species but the estimated value was used for predicting capture of each species. It is not consistent.
  - `p_identified` should be estimated for each species and fishing group (at least species level).
  - In the current situation, it is very difficult to estimate `p_identified` because there is no information about species composition of unidentified birds.
- `ntot` is converted to fixed data as `NTOT` again.
  - I understood the role of `ntot` but I feel it is impossible to give good estimate for `ntot` in this model.
  - Because no information is provided about fluctuation of population in each species, it is very difficult to divide this effect from `q_g`.
- `OVERLAP_O` and `OVERLAP_T` are deployed as covariate for Poisson sampling to explain true catches.
  - But I feel it is better to split OVERLAP into effort and species distribution.
  - In the cases of fisheries stock assessment, effort is usually introduced as an offset.

### Minor changes   
- `prepare-model-data.r` and `run-model.r` are changed a bit because of data preparation.

### CODE REVIEW

**Comment by edwardabraham** [comment]
Thanks for going through this code in such detail and making these suggestions. We agree with some of them, but not with the others. We have explored some of these routes before, and settled on the way of doing things for principled reasons (or because of the larger context that this project sits in, with fisheries using different methods).  Because your pull request is touching on so many things, it is difficult to incorporate. A better process is something along these lines:

1. Raise an issue, with a separate issue for each point
2. We discuss the issue
3. When agreement is reached, raise a pull request that addresses the issue

If you wanted to go ahead  and raise issues (I think one for each of your solid bullet points) then we can discuss them. In this way, the discussion around the points will be clearly maintained.  It is also better to have the discussion before doing the coding.  

That said, @yvanrichard will set up a framework which automatically runs all the models in the `models` directory. This will allow people (like yourself) to develop test models, and we can then compare the results.

**Comment by edwardabraham** [comment]
We have set the project up so that it automatically builds on Travis. You can see the results of the [build process here](https://travis-ci.org/dragonfly-science/seabird-risk-assessment/builds/288896529). In this case, it failed because the `foreach` package needed to be added to the Docker. I have fixed it this with commit d45a88f5ca7aca7305d3ca80e5b850263bb92b96 . If you cherry-pick that commit into your branch and push it, this should update the pull request.  This will then trigger a new build of the project, and hopefully it will all run smoothly.

You may also need to remove the launch of `shinystan` from the bottom of the run model script, if this blocks the script (I made a separate file `view-results.r` for launching `shinystan`).

**Comment by edwardabraham** [comment]
We have set the project up so that it automatically builds on Travis. You can see the results of the [build process here](https://travis-ci.org/dragonfly-science/seabird-risk-assessment/builds/288896529). In this case, it failed because the `foreach` package needed to be added to the Docker image. I have fixed it this with commit d45a88f . If you cherry-pick that commit into your branch and push it, this should update the pull request. This will then trigger a new build of the project, and hopefully it will all run smoothly!

You may also need to remove the launch of `shinystan` from the bottom of the run model script, if this blocks the script (I made a separate file `view-results.r` for launching `shinystan`).

**Comment by otthii** [comment]
@edwardabraham Thank you very much for your kindness and I apologies that too many changes were included one pull request. I understand the situation to build this model and I'd like to discuss about each matter in the issue section separately so please decline this pull request.  
I don't know how Travis CI works but I just used `foreach` package for the purpose of testing code so there is no need to include. Thank you again for your great assistance.

**Comment by edwardabraham** [comment]
Really glad to have you involved, too. And looking forward to next week. Because you have spent this time on it, we will be able to have a really thorough conversation.  

We are using [Docker](www.docker.com) to specify a computation environment. It is great for collaboration as it allows everyone to be using an identical compute environment. I have set one up with all the versions of the R packages pinned, so  there are no annoying bugs caused by slightly different versions.  It is possible to use docker on Windows, Mac, or Linux, and so we can work together between our different operating systems without glitches. It is no trouble to add in new R libraries (see issue #20).

Whenever a commit is made, it is set up so that the code is checked out on Travis, and `make` is run. This runs all the models and produces a report. If the models all run successfully, then you see the `build passing` badge at the top of the Readme on the main Github page.


I will close the pull request now. Cheers!

**Pull request closed without merging**
